[workspace]
members = [
    "src-tauri",
    "src-tauri/crates/aether_core",
    "src-tauri/crates/aether_api",
    "src-tauri/crates/aether_types",
    "src-tauri/crates/aether_cli"
]
resolver = "2"
